spring:
  cloud:
    nacos:
      config:
        group: dev
        server-addr: 127.0.0.1:8848
        file-extension: yml
  application:
    name: gateway-dynamic-route

dynamic:
  config:
    dataId: gateway-json-routes
