spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: app
          # 使用Nacos的话就是nacos的服务名称
          uri: lb://gateway-app
          predicates:
            - Path=/app/**
  application:
    name: gateway-nacos-loadbalance